version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wekids
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 60
      runas: ubuntu