version: '3.7'

services:
  spring:
    # ECR로부터 Spring Boot 이미지를 pull 받아 컨테이너 실행
    image: 992382462285.dkr.ecr.ap-northeast-2.amazonaws.com/wekids-ecr:latest
    restart: always
    ports:
      - "8080:8081"
    container_name: wekids-spring
